# Define the exports for the prx
PSP_BEGIN_EXPORTS

# These four lines are mandatory (although you can add other functions like module_stop)
# syslib is a psynonym for the single mandatory export.
PSP_EXPORT_START(syslib, 0, 0x8000)
PSP_EXPORT_FUNC(module_start)
PSP_EXPORT_VAR(module_info)
PSP_EXPORT_END

PSP_EXPORT_START(psplink, 0, 0x4001)
PSP_EXPORT_FUNC(psplinkPresent)
PSP_EXPORT_FUNC(psplinkHandleException)
PSP_EXPORT_FUNC(psplinkParseCommand)
PSP_EXPORT_FUNC(psplinkPrintPrompt)
PSP_EXPORT_FUNC(psplinkExitShell)
PSP_EXPORT_FUNC(psplinkReferModule)
PSP_EXPORT_FUNC(ttySetWifiHandler)
PSP_EXPORT_FUNC(ttySetUsbHandler)
PSP_EXPORT_FUNC(sceKernelRegisterDefaultExceptionHandler)
PSP_EXPORT_FUNC(sceKernelDcacheWritebackAll)
PSP_EXPORT_FUNC(sceKernelDcacheInvalidateAll)
PSP_EXPORT_FUNC(sceKernelDcacheWritebackInvalidateAll)
PSP_EXPORT_FUNC(sceKernelIcacheInvalidateAll)
PSP_EXPORT_END

PSP_EXPORT_START(sdkbridge, 0, 0x4001)
PSP_EXPORT_FUNC(sceIoAddDrv)
PSP_EXPORT_FUNC(sceIoDelDrv)
PSP_EXPORT_END

PSP_END_EXPORTS
