# Define the exports for the prx
PSP_BEGIN_EXPORTS

# These four lines are mandatory (although you can add other functions like module_stop)
# syslib is a psynonym for the single mandatory export.
PSP_EXPORT_START(syslib, 0, 0x8000)
PSP_EXPORT_FUNC(module_start)
PSP_EXPORT_FUNC(module_stop)
PSP_EXPORT_VAR(module_info)
PSP_EXPORT_END

PSP_EXPORT_START(USBHostFS, 0, 0x4001)
PSP_EXPORT_FUNC(usb_read_data)
PSP_EXPORT_FUNC(usb_write_data)
PSP_EXPORT_FUNC(usb_read_async_data)
PSP_EXPORT_FUNC(usb_write_async_data)
PSP_EXPORT_FUNC(usb_async_flush)
PSP_EXPORT_FUNC(usb_wait_for_connect)
PSP_EXPORT_FUNC(usb_write_bulk_data)
PSP_EXPORT_END

PSP_END_EXPORTS
